from enum import StrEnum


class AuditAction(StrEnum):
    CREATE = "CREATE"

    READ = "READ"
    DOWNLOAD = "DOWNLOAD"

    UPDATE = "UPDATE"

    DELETE = "DELETE"
    RESTORE = "RESTORE"
    PURGE = "PURGE"

    SHARE = "SHARE"
    REVOKE_SHARE = "REVOKE_SHARE"

    SET_TAGS = "SET_TAGS"

    CREATE_REFERENCE = "CREATE_REFERENCE"
    DELETE_REFERENCE = "DELETE_REFERENCE"

    ARCHIVE = "ARCHIVE"
    CHANGE_VISIBILITY = "CHANGE_VISIBILITY"

    CREATE_VERSION = "CREATE_VERSION"
    DOWNLOAD_VERSION = "DOWNLOAD_VERSION"

    GRANT_PERMISSION = "GRANT_PERMISSION"
    REVOKE_PERMISSION = "REVOKE_PERMISSION"

    # Subject-level actions (not tied to a specific object → object_id is null)
    # Hành động cấp-subject (không gắn object cụ thể → object_id null)
    GRANT_SUBJECT_PERMISSION = "GRANT_SUBJECT_PERMISSION"
    REVOKE_SUBJECT_PERMISSION = "REVOKE_SUBJECT_PERMISSION"
    SYNC_SUBJECT = "SYNC_SUBJECT"